create database grocery_store_db;

use grocery_store_db;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

select * from supplier;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

select * from categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

select * from employees;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);
select * from customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from products;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from order_details;

# Analysis Questions

# 1. Customer Insights 

#  How many unique customers have placed orders? 

select COUNT(distinct o.cust_id) as unique_customers
from customers as c
join orders as o
on c.cust_id = o.cust_id;
# OR 

select count(distinct cust_id) from orders;

#  Which customers have placed the highest number of orders?

select c.cust_id, c.cust_name, count(o.ord_id) AS TOTAL_ORDERS
from customers as c
join orders o
on c.cust_id = o.cust_id
group by c.cust_id, c.cust_name
order by total_orders desc limit 4;

# What is the total and average purchase value per customer? 

SELECT * FROM ORDER_DETAILS;

SELECT SUM(TOTAL_PRICE) AS TOTAL FROM ORDER_DETAILS; # TOTAL
SELECT AVG(TOTAL_PRICE) AS AVG_PRICE FROM ORDER_DETAILS; # AVRG PURCHASE AMOUNT

# Who are the top 5 customers by total purchase amount? 

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAILS;

select c.cust_id, c.cust_name,
sum(od.total_price) as total_purchase_amount
from customers c
join orders o
on c.cust_id = o.cust_id
join order_details as od
on od.ord_id = o.ord_id
group by c.cust_id, c.cust_name
order by total_purchase_amount desc
limit 5;

# 2. Product Performance 

# How many products exist in each category?

SELECT COUNT(PROD_NAME) AS PROD_COUNT FROM PRODUCTS;

# What is the average price of products by category?
SELECT * FROM PRODUCTS;
SELECT CAT_ID, ROUND(AVG(PRICE), 2) AS AVRG_PRICE FROM PRODUCTS GROUP BY CAT_ID ;

# Which products have the highest total sales volume (by quantity)?
SELECT P.PROD_NAME, SUM(OD.QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PRODUCTS P
JOIN ORDER_DETAILS AS OD
ON P.PROD_ID = OD.PROD_ID
GROUP BY P.PROD_ID, P.PROD_NAME
ORDER BY TOTAL_QUANTITY_SOLD DESC
LIMIT 5;

# What is the total revenue generated by each product?
SELECT * FROM PRODUCTS;
SELECT * FROM ORDER_DETAILS;

SELECT 
P.PROD_NAME, SUM(OD.TOTAL_PRICE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN ORDER_DETAILS AS OD
ON P.PROD_ID = OD.PROD_ID
GROUP BY P.PROD_ID, P.PROD_NAME
ORDER BY TOTAL_REVENUE DESC;

#  How do product sales vary by category and supplier? 

SELECT C.CAT_NAME, S.SUP_NAME, OD.TOTAL_PRICE, SUM(OD.QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PRODUCTS P
JOIN ORDER_DETAILS AS OD
ON P.PROD_ID = OD.PROD_ID
JOIN CATEGORIES AS C
ON P.CAT_ID = C.CAT_ID
JOIN SUPPLIER AS S
ON P.SUP_ID = S.SUP_ID
GROUP BY C.CAT_NAME, S.SUP_NAME, OD.TOTAL_PRICE
ORDER BY C.CAT_NAME, TOTAL_PRICE DESC;

SELECT * FROM SUPPLIER;

# 3. Sales and Order Trends

# How many orders have been placed in total?
SELECT COUNT(ORD_ID) AS 'TOTAL_ORDERS' FROM ORDERS;

# What is the average value per order?
SELECT ROUND(AVG(TOTAL_PRICE),2) AS ' AVG_VALUE' FROM ORDER_DETAILS;

# On which dates were the most orders placed? 
SELECT ORDER_DATE, COUNT(ORD_ID) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY ORDER_DATE
ORDER BY TOTAL_ORDERS DESC LIMIT 5;

# What are the monthly trends in order volume and revenue? 
select * from orders;
select DATE_FORMAT(o.order_date, '%Y-%m') as month, COUNT(DISTINCT o.ord_id) as order_volume, SUM(total_price) as total_revenue
from orders o
join order_details od
on o.ord_id = od.ord_id
group by DATE_FORMAT(o.order_date, '%Y-%m');

# How do order patterns vary across weekdays and weekends?
SELECT CASE 
WHEN DAYOFWEEK(o.order_date) in (1, 7) then 'Weekend'
else 'Weekday'
end as day_type,
COUNT(DISTINCT o.ord_id) AS total_orders,
SUM(total_price) AS total_revenue
from orders o
join order_details od
on o.ord_id = od.ord_id
group by day_type;

# 4. Supplier Contribution 

# How many suppliers are there in the database? 
SELECT COUNT(SUP_ID) AS 'SUPPLIER_COOUNT' FROM SUPPLIER;

# Which supplier provides the most products? 
SELECT * FROM SUPPLIER;
SELECT * FROM PRODUCTS;

SELECT S.SUP_ID, S.SUP_NAME, COUNT(P.PROD_ID) AS PRODUCT_COUNT
FROM SUPPLIER as S
JOIN PRODUCTS as P
ON S.SUP_ID = P.SUP_ID
GROUP BY S.SUP_ID, S.SUP_NAME
ORDER BY PRODUCT_COUNT DESC;

# What is the average price of products from each supplier?
SELECT * FROM SUPPLIER;
SELECT * FROM PRODUCTS;

select s.sup_id, s.sup_name, round(avg(price),2) as 'avg_price' 
from products as p
join supplier as s
on p.sup_id = s.sup_id
group by s.sup_id , s.sup_name
order by avg_price desc;

# Which suppliers contribute the most to total product sales (by revenue)? 
SELECT * FROM SUPPLIER;
SELECT * FROM PRODUCTS;

select s.sup_id, s.sup_name, SUM(total_price) as total_sales
from supplier as s
join products as p
on s.sup_id = p.sup_id
join order_details od
on p.prod_id = od.prod_id
group by s.sup_id, s.sup_name
order by total_sales desc;

# 5. Employee Performance 

# How many employees have processed orders? 
select count(emp_id) as 'emp_count' from employees;

# Which employees have handled the most orders? 
select * from employees;
select * from orders;

select e.emp_id, e.emp_name, COUNT(o.ord_id) as total_orders_handled
from employees as e
join orders as o
on e.emp_id = o.emp_id
group by e.emp_id, e.emp_name
order by total_orders_handled desc;

# What is the total sales value processed by each employee? 
select * from employees;
select * from orders;
select * from order_details;

select e.emp_id, e.emp_name, SUM(od.total_price) as total_sales
from employees as e
join orders as o
on e.emp_id = o.emp_id
join order_details as od
on o.ord_id = od.ord_id
group by e.emp_id, e.emp_name
order by total_sales desc;

# What is the average order value handled per employee?
select e.emp_id, e.emp_name, round(avg(od.total_price),2) as avg_sales
from employees as e
join orders as o
on e.emp_id = o.emp_id
join order_details as od
on o.ord_id = od.ord_id
group by e.emp_id, e.emp_name
order by avg_sales desc;

# 6. Order Details Deep Dive 

# What is the relationship between quantity ordered and total price? 
select * from order_details;

select quantity, round(avg(total_price),2) as avg_total_price
from order_details
group by quantity
order by quantity;

# What is the average quantity ordered per product? 
select * from order_details;
select * from products;

select p.prod_id, p.prod_name, round(avg(od.quantity), 0) as 'avg_order_quantity'
from products as p
join order_details as od
on p.prod_id = od.prod_id
group by p.prod_id, p.prod_name
order by avg_order_quantity desc;

# How does the unit price vary across products and orders? 

select od.ord_id, p.prod_name, od.quantity, ROUND(od.total_price / od.quantity, 2) as unit_price
from order_details od
join products p
on od.prod_id = p.prod_id
where od.quantity > 0
order by p.prod_name, od.ord_id;

select * from customers;
select * from order_details;
select * from products;